# Generated by Django 2.0.2 on 2018-04-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='communication.Profile'),
        ),
    ]
