# Generated by Django 2.0.2 on 2018-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180408_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
