# Generated by Django 2.0.2 on 2018-04-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20180409_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
