# Generated by Django 2.0.2 on 2018-03-27 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(max_length=3)),
                ('start_time', models.DateField()),
                ('pace', models.IntegerField(max_length=4)),
                ('location', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=300)),
                ('num_participants', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('strava_link', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=250)),
                ('road_surfaces', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=10)),
                ('ride_code', models.IntegerField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='featured',
            name='f_ride_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Ride'),
        ),
    ]
