# Generated by Django 2.0.2 on 2018-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pace',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
