# Generated by Django 2.0.2 on 2018-03-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_auto_20180327_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='ride_code',
        ),
    ]
