# Generated by Django 2.0.2 on 2018-03-28 14:40

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_remove_ride_ride_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location_name', location_field.models.plain.PlainLocationField(default='haymarket', max_length=63)),
            ],
        ),
    ]
