# Generated by Django 2.0.2 on 2018-03-28 14:43

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0004_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='f_location_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appOne.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location_name',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
