# Generated by Django 2.0.2 on 2018-03-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0005_auto_20180328_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='location',
            new_name='ride_name',
        ),
    ]
