# Generated by Django 2.0.2 on 2018-04-07 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appOne', '0006_auto_20180328_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('f_ride', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appOne.Ride')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='f_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appOne.Profile'),
        ),
    ]
